# Imagen base
FROM node:18-alpine

# Directorio de trabajo
WORKDIR /app

# Copiar dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Compilar NestJS
RUN npm run build

# Exponer puerto
EXPOSE 3000

# Comando de arranque
CMD ["npm", "run", "start:prod"]
